# This project is about predicting the heart disease using Multiple classification Algorithm. This project uses cleaned dataset( i.e cleaned in eda project)

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv('Cleaned_Heart_Disease.csv')

In [3]:
data

,Unnamed: 0,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,...,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease,Age_Group,Cholesterol_Category,BP_Category,Heart Disease Num
0,0,75,Female,228,119,66,Current,Heavy,1,No,...,Yes,8,119,Yes,Atypical Angina,Yes,Senior,Borderline,Normal,1
1,1,48,Male,204,165,62,Current,Never,5,No,...,No,9,70,Yes,Typical Angina,No,Middle-Aged,Borderline,High,0
2,2,53,Male,234,91,67,Never,Heavy,3,Yes,...,Yes,5,196,Yes,Atypical Angina,Yes,Middle-Aged,Borderline,Normal,1
3,3,69,Female,192,90,72,Current,Never,4,No,...,No,7,107,Yes,Non-anginal Pain,No,Senior,Normal,Normal,0
4,4,62,Female,172,163,93,Never,Never,6,No,...,No,2,183,Yes,Asymptomatic,No,Senior,Normal,High,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,56,Female,269,111,86,Never,Heavy,5,No,...,Yes,10,120,No,Non-anginal Pain,Yes,Middle-Aged,High,Normal,1
996,996,78,Female,334,145,76,Never,Never,6,No,...,No,10,196,Yes,Typical Angina,Yes,Senior,High,High,1
997,997,79,Male,151,179,81,Never,Moderate,4,Yes,...,Yes,8,189,Yes,Asymptomatic,No,Senior,Normal,High,0
998,998,60,Female,326,151,68,Former,Never,8,Yes,...,No,5,174,Yes,Atypical Angina,Yes,Middle-Aged,High,High,1
999,999,53,Male,226,116,82,Current,Never,6,No,...,Yes,5,161,Yes,Asymptomatic,Yes,Middle-Aged,Borderline,Normal,1

In [4]:
data.sample(10)

,Unnamed: 0,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,...,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease,Age_Group,Cholesterol_Category,BP_Category,Heart Disease Num
759,759,71,Female,161,175,78,Never,Heavy,1,No,...,Yes,2,114,No,Non-anginal Pain,No,Senior,Normal,High,0
487,487,54,Female,188,163,80,Current,Moderate,7,Yes,...,No,3,106,No,Atypical Angina,No,Middle-Aged,Normal,High,0
749,749,66,Male,154,128,69,Former,Heavy,1,No,...,Yes,3,169,Yes,Non-anginal Pain,No,Senior,Normal,Elevated,0
668,668,72,Male,343,113,89,Current,Moderate,2,No,...,Yes,10,166,No,Non-anginal Pain,Yes,Senior,High,Normal,1
516,516,68,Female,206,104,65,Never,Heavy,9,Yes,...,Yes,8,102,No,Atypical Angina,Yes,Senior,Borderline,Normal,1
630,630,68,Female,332,125,74,Current,Moderate,8,No,...,No,6,103,No,Non-anginal Pain,Yes,Senior,High,Elevated,1
109,109,37,Female,226,173,86,Current,Moderate,7,No,...,No,2,139,No,Asymptomatic,No,Young,Borderline,High,0
257,257,26,Female,280,144,60,Never,Heavy,7,Yes,...,No,6,194,No,Atypical Angina,No,Young,High,High,0
532,532,42,Male,297,144,77,Never,Moderate,2,No,...,Yes,9,194,No,Non-anginal Pain,No,Middle-Aged,High,High,0
802,802,49,Male,343,106,89,Former,Heavy,3,Yes,...,Yes,10,70,No,Asymptomatic,No,Middle-Aged,High,Normal,0

In [5]:
data.shape

(1000, 21)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               1000 non-null   int64
 1   Age                      1000 non-null   int64
 2   Gender                   1000 non-null   object
 3   Cholesterol              1000 non-null   int64
 4   Blood Pressure           1000 non-null   int64
 5   Heart Rate               1000 non-null   int64
 6   Smoking                  1000 non-null   object
 7   Alcohol Intake           1000 non-null   object
 8   Exercise Hours           1000 non-null   int64
 9   Family History           1000 non-null   object
 10  Diabetes                 1000 non-null   object
 11  Obesity                  1000 non-null   object
 12  Stress Level             1000 non-null   int64
 13  Blood Sugar              1000 non-null   int64
 14  Exercise Induced Angina  1000 non-null   object
 15  Chest Pain Type          1000 non-null   object
 16  Heart Disease            1000 non-null   object
 17  Age_Group                1000 non-null   object
 18  Cholesterol_Category     1000 non-null   object
 19  BP_Category              1000 non-null   object
 20  Heart Disease Num        1000 non-null   int64
dtypes: int64(9), object(12)
memory usage: 164.2+ KB

In [7]:
data.isnull().sum()

Unnamed: 0                 0
Age                        0
Gender                     0
Cholesterol                0
Blood Pressure             0
Heart Rate                 0
Smoking                    0
Alcohol Intake             0
Exercise Hours             0
Family History             0
Diabetes                   0
Obesity                    0
Stress Level               0
Blood Sugar                0
Exercise Induced Angina    0
Chest Pain Type            0
Heart Disease              0
Age_Group                  0
Cholesterol_Category       0
BP_Category                0
Heart Disease Num          0
dtype: int64

In [8]:
data.duplicated().sum()

np.int64(0)

In [9]:
data.columns

Index(['Unnamed: 0', 'Age', 'Gender', 'Cholesterol', 'Blood Pressure',
       'Heart Rate', 'Smoking', 'Alcohol Intake', 'Exercise Hours',
       'Family History', 'Diabetes', 'Obesity', 'Stress Level', 'Blood Sugar',
       'Exercise Induced Angina', 'Chest Pain Type', 'Heart Disease',
       'Age_Group', 'Cholesterol_Category', 'BP_Category',
       'Heart Disease Num'],
      dtype='object')

'Unnamed: 0' is unnecessary feature. 

'Heart Disease' is a categorical features which is converted into 'Heart Disease Num'

since the features ['Age_Group', 'Cholesterol_Category', 'BP_Category', ] are the binned duplicates of Age, Cholesterol, Blood Pressure — keeping both causes redundancy.

Droping features ['Unnamed: 0','Heart Disease' , 'Age_Group', 'Cholesterol_Category', 'BP_Category' ]

In [10]:
data.drop(columns=['Unnamed: 0', 'Heart Disease', 'Age_Group', 'Cholesterol_Category', 'BP_Category'], inplace=True)

In [11]:
data.sample(10)

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease Num
818,44,Female,185,148,64,Former,Moderate,9,Yes,Yes,No,3,120,No,Atypical Angina,0
849,69,Female,272,122,97,Current,Never,1,Yes,No,No,5,118,No,Atypical Angina,1
91,38,Male,215,138,61,Former,Heavy,1,No,Yes,Yes,10,198,Yes,Atypical Angina,0
438,69,Female,267,140,72,Current,Heavy,0,Yes,No,Yes,4,169,Yes,Atypical Angina,1
909,56,Male,247,113,76,Never,Heavy,1,Yes,No,No,9,86,Yes,Asymptomatic,1
432,79,Male,222,150,65,Current,Moderate,6,No,Yes,Yes,1,71,No,Asymptomatic,1
959,62,Male,206,177,83,Former,Moderate,5,Yes,Yes,Yes,5,110,Yes,Non-anginal Pain,1
654,76,Female,159,143,83,Never,Heavy,5,No,Yes,Yes,9,96,No,Asymptomatic,0
203,68,Male,159,148,82,Never,Heavy,8,No,No,Yes,3,159,Yes,Non-anginal Pain,0
88,61,Female,184,119,77,Never,Never,8,No,Yes,Yes,10,92,Yes,Atypical Angina,0

In [12]:
data.shape

(1000, 16)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1000 non-null   int64
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64
 3   Blood Pressure           1000 non-null   int64
 4   Heart Rate               1000 non-null   int64
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           1000 non-null   object
 7   Exercise Hours           1000 non-null   int64
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64
 12  Blood Sugar              1000 non-null   int64
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   object
 15  Heart Disease Num        1000 non-null   int64
dtypes: int64(8), object(8)
memory usage: 125.1+ KB

In [14]:
# seperating Features and Target
x = data.drop(columns=['Heart Disease Num'])
y = data['Heart Disease Num']

In [15]:
x.shape, y.shape

((1000, 15), (1000,))

In [16]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1000 non-null   int64
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64
 3   Blood Pressure           1000 non-null   int64
 4   Heart Rate               1000 non-null   int64
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           1000 non-null   object
 7   Exercise Hours           1000 non-null   int64
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64
 12  Blood Sugar              1000 non-null   int64
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   object
dtypes: int64(7), object(8)
memory usage: 117.3+ KB

In [17]:
numerical_cols =['Age', 'Cholesterol', 'Blood Pressure', 'Heart Rate', 'Exercise Hours', 'Stress Level', 'Blood Sugar']
categorical_cols = ['Gender', 'Smoking', 'Alcohol Intake', 'Family History', 'Diabetes', 'Obesity', 'Exercise Induced Angina', 'Chest Pain Type']

In [18]:
from sklearn.preprocessing import OneHotEncoder
# initializating encoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

# fit and transform categorical featues
encoded_array = encoder.fit_transform(x[categorical_cols])

In [19]:
# getting all encoded categorical features
encoded_cols = encoder.get_feature_names_out(categorical_cols)

In [20]:
encoded_cols

array(['Gender_Female', 'Gender_Male', 'Smoking_Current',
       'Smoking_Former', 'Smoking_Never', 'Alcohol Intake_Heavy',
       'Alcohol Intake_Moderate', 'Alcohol Intake_Never',
       'Family History_No', 'Family History_Yes', 'Diabetes_No',
       'Diabetes_Yes', 'Obesity_No', 'Obesity_Yes',
       'Exercise Induced Angina_No', 'Exercise Induced Angina_Yes',
       'Chest Pain Type_Asymptomatic', 'Chest Pain Type_Atypical Angina',
       'Chest Pain Type_Non-anginal Pain',
       'Chest Pain Type_Typical Angina'], dtype=object)

In [21]:
# create a new dataframe with new encoded categorical features
encoded_df = pd.DataFrame(encoded_array, columns=encoded_cols, index=x.index)

# Concatenate numerical features and encoded categorical features
x_encoded = pd.concat([x[numerical_cols], encoded_df], axis=1)

In [22]:
x_encoded.sample(10)

,Age,Cholesterol,Blood Pressure,Heart Rate,Exercise Hours,Stress Level,Blood Sugar,Gender_Female,Gender_Male,Smoking_Current,...,Diabetes_No,Diabetes_Yes,Obesity_No,Obesity_Yes,Exercise Induced Angina_No,Exercise Induced Angina_Yes,Chest Pain Type_Asymptomatic,Chest Pain Type_Atypical Angina,Chest Pain Type_Non-anginal Pain,Chest Pain Type_Typical Angina
156,64,250,98,79,0,4,105,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
642,42,288,161,82,1,7,71,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
481,59,166,139,64,9,3,145,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
890,37,283,115,80,6,4,86,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
19,74,298,148,70,9,8,157,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
377,59,339,172,98,1,3,126,0.0,1.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
881,59,154,114,99,6,7,182,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
670,74,187,129,94,4,1,196,0.0,1.0,1.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
721,30,150,165,72,8,9,70,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
274,48,317,132,96,8,6,164,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [23]:
x_encoded.shape

(1000, 27)

In [24]:
from sklearn.model_selection import  train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_encoded,y, test_size= 0.2, random_state=42, stratify=y)

In [25]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 27), (200, 27), (800,), (200,))

In [26]:
# features scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [27]:
x_test_scaled

array([[ 1.713725  , -0.46799363,  0.53599413, ..., -0.56772709,
        -0.58312392, -0.57350122],
       [-1.55753821,  0.82195573, -0.94970388, ...,  1.76140969,
        -0.58312392, -0.57350122],
       [-0.65954439,  1.18314156, -0.68304014, ...,  1.76140969,
        -0.58312392, -0.57350122],
       ...,
       [-1.68582305,  1.64752333, -0.53066085, ..., -0.56772709,
        -0.58312392, -0.57350122],
       [-0.33883231,  0.95955033, -1.40684173, ..., -0.56772709,
         1.71490137, -0.57350122],
       [-1.42925338,  1.5615267 ,  1.33598536, ..., -0.56772709,
        -0.58312392, -0.57350122]], shape=(200, 27))

In [28]:
x_train_scaled

array([[-0.46711714, -1.49995312, -1.06398834, ..., -0.56772709,
         1.71490137, -0.57350122],
       [ 1.52129775,  0.06518544, -0.30209193, ..., -0.56772709,
        -0.58312392,  1.74367544],
       [-1.62168063, -0.05520983,  0.91694233, ..., -0.56772709,
        -0.58312392,  1.74367544],
       ...,
       [ 0.23844943,  0.49516856, -1.52112619, ...,  1.76140969,
        -0.58312392, -0.57350122],
       [ 0.43087668,  0.83915506, -0.41637639, ...,  1.76140969,
        -0.58312392, -0.57350122],
       [ 1.58544017, -0.02081118, -1.52112619, ..., -0.56772709,
        -0.58312392, -0.57350122]], shape=(800, 27))

In [29]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
logistic_regression = LogisticRegression(max_iter=1000, random_state=42)
logistic_regression

LogisticRegression(max_iter=1000, random_state=42)

In [30]:
logistic_regression.fit(x_train, y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=42)

In [31]:
y_pred_logistic_regression = logistic_regression.predict(x_test)
y_pred_logistic_regression

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0])

In [32]:
y_test.shape, y_test.value_counts()

((200,),
 Heart Disease Num
 0    122
 1     78
 Name: count, dtype: int64)

In [33]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluation metrics of Logistic Regression
logistic_regression_conf_matrix = confusion_matrix(y_test, y_pred_logistic_regression)
logistic_regression_accuracy = accuracy_score(y_test, y_pred_logistic_regression)
logistic_regression_report = classification_report(y_test, y_pred_logistic_regression)

print('Logistic Regression Confusion Matrix:\n', logistic_regression_conf_matrix)
print('\nLogistic Regression Accuracy:', logistic_regression_accuracy)
print('\nLogistic Regression Classification Report:\n', logistic_regression_report)

Logistic Regression Confusion Matrix:
 [[111  11]
 [ 18  60]]

Logistic Regression Accuracy: 0.855

Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.91      0.88       122
           1       0.85      0.77      0.81        78

    accuracy                           0.85       200
   macro avg       0.85      0.84      0.84       200
weighted avg       0.85      0.85      0.85       200

In [34]:
# Hyperparameter tuning
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import GridSearchCV

param_grid = [
    {
        # Solver 1: lbfgs (Supports L2 or None)
        "solver": ["lbfgs"],
        "penalty": ["l2", None],
        "C": [0.001, 0.01, 0.1, 1, 10, 100],
    },
    {
        # Solver 2: liblinear (Supports L1 or L2)
        "solver": ["liblinear"],
        "penalty": ["l1", "l2"],
        "C": [0.001, 0.01, 0.1, 1, 10, 100],
    }
]

logistic_regression_grid = GridSearchCV(logistic_regression, param_grid=param_grid)
logistic_regression_grid.fit(x_train,y_train)

GridSearchCV(estimator=LogisticRegression(max_iter=1000, random_state=42),
             param_grid=[{'C': [0.001, 0.01, 0.1, 1, 10, 100],
                          'penalty': ['l2', None], 'solver': ['lbfgs']},
                         {'C': [0.001, 0.01, 0.1, 1, 10, 100],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']}])

In [35]:
logistic_regression_grid.best_params_

{'C': 0.001, 'penalty': 'l2', 'solver': 'lbfgs'}

In [36]:
logistic_regression_tuned = LogisticRegression(**logistic_regression_grid.best_params_, random_state=42)
logistic_regression_tuned.fit(x_train, y_train)

LogisticRegression(C=0.001, random_state=42)

In [37]:
y_pred_logistic_regression_tuned = logistic_regression_tuned.predict(x_test)
y_pred_logistic_regression_tuned

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0])

In [38]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluation metrics of Logistic Regression ( Tuned )
logistic_regression_tuned_conf_matrix = confusion_matrix(y_test, y_pred_logistic_regression_tuned)
logistic_regression_tuned_accuracy = accuracy_score(y_test, y_pred_logistic_regression_tuned)
logistic_regression_tuned_report = classification_report(y_test, y_pred_logistic_regression_tuned)

print('Logistic Regression (tuned) Confusion Matrix:\n', logistic_regression_tuned_conf_matrix)
print('\nLogistic Regression (tuned) Accuracy:', logistic_regression_tuned_accuracy)
print('\nLogistic Regression (tuned) Classification Report:\n', logistic_regression_tuned_report)

Logistic Regression (tuned) Confusion Matrix:
 [[114   8]
 [ 15  63]]

Logistic Regression (tuned) Accuracy: 0.885

Logistic Regression (tuned) Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.93      0.91       122
           1       0.89      0.81      0.85        78

    accuracy                           0.89       200
   macro avg       0.89      0.87      0.88       200
weighted avg       0.89      0.89      0.88       200

In [39]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier

KNeighborsClassifier()

In [40]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [41]:
y_pred_classifier = classifier.predict(x_test)
y_pred_classifier

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0])

In [42]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluation metrics of KNeighborsClassifier
classifier_conf_matrix = confusion_matrix(y_test, y_pred_classifier)
classifier_accuracy = accuracy_score(y_test, y_pred_classifier)
classifier_report = classification_report(y_test, y_pred_classifier)

print('Classifier Confusion Matrix:\n', classifier_conf_matrix)
print('\nClassifier Accuracy:', classifier_accuracy)
print('\nClassifer Classification Report:\n', classifier_report)

Classifier Confusion Matrix:
 [[111  11]
 [ 10  68]]

Classifier Accuracy: 0.895

Classifer Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.91      0.91       122
           1       0.86      0.87      0.87        78

    accuracy                           0.90       200
   macro avg       0.89      0.89      0.89       200
weighted avg       0.90      0.90      0.90       200

In [43]:
# Hyperparameter tuning for Classifier
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import GridSearchCV
classifier_param = {
              'n_neighbors' : list(range(30)),
              'p' : [1,2]
              }

classifier_grid = GridSearchCV(classifier, param_grid = classifier_param)
classifier_grid.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
                                         22, 23, 24, 25, 26, 27, 28, 29],
                         'p': [1, 2]})

In [44]:
classifier_grid.best_params_

{'n_neighbors': 21, 'p': 1}

In [45]:
classifier_tuned = KNeighborsClassifier(**classifier_grid.best_params_)
classifier_tuned.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=21, p=1)

In [46]:
y_pred_classifier_tuned = classifier_tuned.predict(x_test)
y_pred_classifier_tuned

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0])

In [47]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluation metrics of Classifier (tuned)
classifier_tuned_conf_matrix = confusion_matrix(y_test, y_pred_classifier_tuned)
classifier_tuned_accuracy = accuracy_score(y_test, y_pred_classifier_tuned)
classifier_tuned_report = classification_report(y_test, y_pred_classifier_tuned)

print('Classifier (Tuned) Confusion Matrix:\n', classifier_tuned_conf_matrix)
print('\nClassifier (Tuned) Accuracy:', classifier_tuned_accuracy)
print('\nClassifer (Tuned) Classification Report:\n', classifier_tuned_report)

Classifier (Tuned) Confusion Matrix:
 [[117   5]
 [  6  72]]

Classifier (Tuned) Accuracy: 0.945

Classifer (Tuned) Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96       122
           1       0.94      0.92      0.93        78

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.94       200
weighted avg       0.94      0.94      0.94       200